services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql
    networks:
      - my-network

  php:
    build:
      context: .
      args:
        USER_ID: "${UID}"
        GROUP_ID: "${GID}"
    user: "${UID}:${GID}"
    image: php
    container_name: php
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my-network

  node:
    image: node:23.7.0-alpine3.20
    container_name: node
    user: "${UID}:${GID}"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    expose:
      - "5173:5173"
    networks:
      - my-network

volumes:
  db-data:
  db-logs:

networks:
  my-network:
    driver: bridge