services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - my-network

  php:
    build:
      context: .
    image: php
    container_name: php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-logs:/var/log/mysql
    networks:
      - my-network

  node:
    image: node:23.7.0-alpine3.20
    container_name: node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - my-network

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - my-network

volumes:
  db-data:
  db-logs:

networks:
  my-network:
    driver: bridge
